// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package sde is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	TypeIdRequest
	TypeNameSearchRequest
	TypeNameRequest
	TypeResponse
	TypesResponse
	TypeNameAndIdResponse
	Type
*/
package sde

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Rserved for future purposes where the sde is loaded without removing locales
type Locale int32

const (
	Locale_EN Locale = 0
	Locale_DE Locale = 1
	Locale_FR Locale = 2
	Locale_JA Locale = 3
	Locale_RU Locale = 4
	Locale_ZH Locale = 5
)

var Locale_name = map[int32]string{
	0: "EN",
	1: "DE",
	2: "FR",
	3: "JA",
	4: "RU",
	5: "ZH",
}
var Locale_value = map[string]int32{
	"EN": 0,
	"DE": 1,
	"FR": 2,
	"JA": 3,
	"RU": 4,
	"ZH": 5,
}

func (x Locale) String() string {
	return proto.EnumName(Locale_name, int32(x))
}
func (Locale) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TypeIdRequest struct {
	TypeId []int32 `protobuf:"varint,1,rep,packed,name=TypeId" json:"TypeId,omitempty"`
	Locale Locale  `protobuf:"varint,2,opt,name=Locale,enum=sde.Locale" json:"Locale,omitempty"`
}

func (m *TypeIdRequest) Reset()                    { *m = TypeIdRequest{} }
func (m *TypeIdRequest) String() string            { return proto.CompactTextString(m) }
func (*TypeIdRequest) ProtoMessage()               {}
func (*TypeIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TypeIdRequest) GetTypeId() []int32 {
	if m != nil {
		return m.TypeId
	}
	return nil
}

func (m *TypeIdRequest) GetLocale() Locale {
	if m != nil {
		return m.Locale
	}
	return Locale_EN
}

type TypeNameSearchRequest struct {
	TypeName []string `protobuf:"bytes,1,rep,name=TypeName" json:"TypeName,omitempty"`
	Locale   Locale   `protobuf:"varint,2,opt,name=Locale,enum=sde.Locale" json:"Locale,omitempty"`
}

func (m *TypeNameSearchRequest) Reset()                    { *m = TypeNameSearchRequest{} }
func (m *TypeNameSearchRequest) String() string            { return proto.CompactTextString(m) }
func (*TypeNameSearchRequest) ProtoMessage()               {}
func (*TypeNameSearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TypeNameSearchRequest) GetTypeName() []string {
	if m != nil {
		return m.TypeName
	}
	return nil
}

func (m *TypeNameSearchRequest) GetLocale() Locale {
	if m != nil {
		return m.Locale
	}
	return Locale_EN
}

type TypeNameRequest struct {
	TypeName string `protobuf:"bytes,1,opt,name=TypeName" json:"TypeName,omitempty"`
	Locale   Locale `protobuf:"varint,2,opt,name=Locale,enum=sde.Locale" json:"Locale,omitempty"`
}

func (m *TypeNameRequest) Reset()                    { *m = TypeNameRequest{} }
func (m *TypeNameRequest) String() string            { return proto.CompactTextString(m) }
func (*TypeNameRequest) ProtoMessage()               {}
func (*TypeNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TypeNameRequest) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *TypeNameRequest) GetLocale() Locale {
	if m != nil {
		return m.Locale
	}
	return Locale_EN
}

type TypeResponse struct {
	Type *Type `protobuf:"bytes,1,opt,name=Type" json:"Type,omitempty"`
}

func (m *TypeResponse) Reset()                    { *m = TypeResponse{} }
func (m *TypeResponse) String() string            { return proto.CompactTextString(m) }
func (*TypeResponse) ProtoMessage()               {}
func (*TypeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TypeResponse) GetType() *Type {
	if m != nil {
		return m.Type
	}
	return nil
}

type TypesResponse struct {
	Type []*Type `protobuf:"bytes,1,rep,name=Type" json:"Type,omitempty"`
}

func (m *TypesResponse) Reset()                    { *m = TypesResponse{} }
func (m *TypesResponse) String() string            { return proto.CompactTextString(m) }
func (*TypesResponse) ProtoMessage()               {}
func (*TypesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TypesResponse) GetType() []*Type {
	if m != nil {
		return m.Type
	}
	return nil
}

type TypeNameAndIdResponse struct {
	TypeId []int32  `protobuf:"varint,1,rep,packed,name=TypeId" json:"TypeId,omitempty"`
	Name   []string `protobuf:"bytes,2,rep,name=Name" json:"Name,omitempty"`
}

func (m *TypeNameAndIdResponse) Reset()                    { *m = TypeNameAndIdResponse{} }
func (m *TypeNameAndIdResponse) String() string            { return proto.CompactTextString(m) }
func (*TypeNameAndIdResponse) ProtoMessage()               {}
func (*TypeNameAndIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TypeNameAndIdResponse) GetTypeId() []int32 {
	if m != nil {
		return m.TypeId
	}
	return nil
}

func (m *TypeNameAndIdResponse) GetName() []string {
	if m != nil {
		return m.Name
	}
	return nil
}

type Type struct {
	TypeId        int32   `protobuf:"varint,1,opt,name=TypeId" json:"TypeId,omitempty"`
	Capacity      float32 `protobuf:"fixed32,3,opt,name=Capacity" json:"Capacity,omitempty"`
	Description   string  `protobuf:"bytes,4,opt,name=Description" json:"Description,omitempty"`
	GraphicId     int32   `protobuf:"varint,5,opt,name=GraphicId" json:"GraphicId,omitempty"`
	GroupId       int32   `protobuf:"varint,6,opt,name=GroupId" json:"GroupId,omitempty"`
	IconId        int32   `protobuf:"varint,7,opt,name=IconId" json:"IconId,omitempty"`
	MarketGroupId int32   `protobuf:"varint,8,opt,name=MarketGroupId" json:"MarketGroupId,omitempty"`
	Mass          float32 `protobuf:"fixed32,9,opt,name=Mass" json:"Mass,omitempty"`
	Name          string  `protobuf:"bytes,10,opt,name=Name" json:"Name,omitempty"`
	PortionSize   int32   `protobuf:"varint,11,opt,name=PortionSize" json:"PortionSize,omitempty"`
	Published     bool    `protobuf:"varint,12,opt,name=Published" json:"Published,omitempty"`
	Radius        float32 `protobuf:"fixed32,13,opt,name=Radius" json:"Radius,omitempty"`
	Volume        float32 `protobuf:"fixed32,15,opt,name=Volume" json:"Volume,omitempty"`
}

func (m *Type) Reset()                    { *m = Type{} }
func (m *Type) String() string            { return proto.CompactTextString(m) }
func (*Type) ProtoMessage()               {}
func (*Type) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Type) GetTypeId() int32 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *Type) GetCapacity() float32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Type) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Type) GetGraphicId() int32 {
	if m != nil {
		return m.GraphicId
	}
	return 0
}

func (m *Type) GetGroupId() int32 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *Type) GetIconId() int32 {
	if m != nil {
		return m.IconId
	}
	return 0
}

func (m *Type) GetMarketGroupId() int32 {
	if m != nil {
		return m.MarketGroupId
	}
	return 0
}

func (m *Type) GetMass() float32 {
	if m != nil {
		return m.Mass
	}
	return 0
}

func (m *Type) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Type) GetPortionSize() int32 {
	if m != nil {
		return m.PortionSize
	}
	return 0
}

func (m *Type) GetPublished() bool {
	if m != nil {
		return m.Published
	}
	return false
}

func (m *Type) GetRadius() float32 {
	if m != nil {
		return m.Radius
	}
	return 0
}

func (m *Type) GetVolume() float32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func init() {
	proto.RegisterType((*TypeIdRequest)(nil), "sde.TypeIdRequest")
	proto.RegisterType((*TypeNameSearchRequest)(nil), "sde.TypeNameSearchRequest")
	proto.RegisterType((*TypeNameRequest)(nil), "sde.TypeNameRequest")
	proto.RegisterType((*TypeResponse)(nil), "sde.TypeResponse")
	proto.RegisterType((*TypesResponse)(nil), "sde.TypesResponse")
	proto.RegisterType((*TypeNameAndIdResponse)(nil), "sde.TypeNameAndIdResponse")
	proto.RegisterType((*Type)(nil), "sde.Type")
	proto.RegisterEnum("sde.Locale", Locale_name, Locale_value)
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x6d, 0xd2, 0x8f, 0xb5, 0xb7, 0xeb, 0x16, 0x2c, 0x98, 0xac, 0x0a, 0xa4, 0x2a, 0xf0, 0x50,
	0x21, 0xd1, 0x87, 0xf2, 0xc2, 0x0b, 0x42, 0x63, 0x5d, 0x47, 0xa7, 0x6d, 0x1a, 0x1e, 0x20, 0xc4,
	0x5b, 0x16, 0x5b, 0x6a, 0x44, 0x17, 0x07, 0x3b, 0x41, 0x2a, 0xff, 0x85, 0x3f, 0xc8, 0xaf, 0x40,
	0xbe, 0xce, 0xa7, 0xe8, 0x10, 0x3c, 0x5d, 0xdf, 0xe3, 0x7b, 0x8e, 0x8f, 0x6f, 0xae, 0x03, 0x23,
	0x2d, 0xd4, 0xf7, 0x28, 0x14, 0xb3, 0x44, 0xc9, 0x54, 0x92, 0xb6, 0xe6, 0xc2, 0xbf, 0x80, 0xd1,
	0x87, 0x6d, 0x22, 0x56, 0x9c, 0x89, 0x6f, 0x99, 0xd0, 0x29, 0x39, 0x82, 0x9e, 0x05, 0xa8, 0x33,
	0x69, 0x4f, 0xbb, 0x2c, 0xcf, 0xc8, 0x53, 0xe8, 0x5d, 0xc8, 0x30, 0xd8, 0x08, 0xea, 0x4e, 0x9c,
	0xe9, 0xc1, 0x7c, 0x38, 0xd3, 0x5c, 0xcc, 0x2c, 0xc4, 0xf2, 0x2d, 0xff, 0x33, 0x3c, 0x32, 0xe5,
	0x57, 0xc1, 0x9d, 0xb8, 0x11, 0x81, 0x0a, 0xd7, 0x85, 0xea, 0x18, 0xfa, 0xc5, 0x06, 0xea, 0x0e,
	0x58, 0x99, 0xff, 0x9b, 0x32, 0x83, 0xc3, 0x82, 0xb0, 0x5b, 0xd3, 0xf9, 0x7f, 0xcd, 0x17, 0xb0,
	0x6f, 0x08, 0x4c, 0xe8, 0x44, 0xc6, 0x5a, 0x90, 0x27, 0xd0, 0x31, 0x39, 0x8a, 0x0d, 0xe7, 0x03,
	0xa4, 0x60, 0x01, 0xc2, 0xfe, 0xcc, 0xb6, 0x4a, 0xef, 0xa8, 0x6f, 0xef, 0xaa, 0x3f, 0xa9, 0x9a,
	0x71, 0x1c, 0x73, 0xd3, 0xe1, 0x9c, 0x77, 0x5f, 0x8b, 0x09, 0x74, 0xf0, 0x32, 0x2e, 0x36, 0x08,
	0xd7, 0xfe, 0x2f, 0xd7, 0x1e, 0xd2, 0x20, 0x39, 0x35, 0xd2, 0x18, 0xfa, 0x27, 0x41, 0x12, 0x84,
	0x51, 0xba, 0xa5, 0xed, 0x89, 0x33, 0x75, 0x59, 0x99, 0x93, 0x09, 0x0c, 0x17, 0x42, 0x87, 0x2a,
	0x4a, 0xd2, 0x48, 0xc6, 0xb4, 0x83, 0x4d, 0xaa, 0x43, 0xe4, 0x31, 0x0c, 0xce, 0x54, 0x90, 0xac,
	0xa3, 0x70, 0xc5, 0x69, 0x17, 0x85, 0x2b, 0x80, 0x50, 0xd8, 0x3b, 0x53, 0x32, 0x4b, 0x56, 0x9c,
	0xf6, 0x70, 0xaf, 0x48, 0x8d, 0x9b, 0x55, 0x28, 0xe3, 0x15, 0xa7, 0x7b, 0xd6, 0x8d, 0xcd, 0xc8,
	0x33, 0x18, 0x5d, 0x06, 0xea, 0xab, 0x48, 0x0b, 0x5e, 0x1f, 0xb7, 0x9b, 0xa0, 0xb9, 0xe8, 0x65,
	0xa0, 0x35, 0x1d, 0xa0, 0x5f, 0x5c, 0x97, 0x97, 0x07, 0x34, 0x89, 0x6b, 0xe3, 0xff, 0x5a, 0x2a,
	0x63, 0xf4, 0x26, 0xfa, 0x21, 0xe8, 0x10, 0xb5, 0xea, 0x90, 0xf1, 0x7f, 0x9d, 0xdd, 0x6e, 0x22,
	0xbd, 0x16, 0x9c, 0xee, 0x4f, 0x9c, 0x69, 0x9f, 0x55, 0x80, 0x71, 0xc9, 0x02, 0x1e, 0x65, 0x9a,
	0x8e, 0xf0, 0xa4, 0x3c, 0x33, 0xf8, 0x27, 0xb9, 0xc9, 0xee, 0x04, 0x3d, 0xb4, 0xb8, 0xcd, 0x9e,
	0xbf, 0x2a, 0xa6, 0x86, 0xf4, 0xc0, 0x3d, 0xbd, 0xf2, 0x5a, 0x26, 0x2e, 0x4e, 0x3d, 0xc7, 0xc4,
	0x25, 0xf3, 0x5c, 0x13, 0xcf, 0x8f, 0xbd, 0xb6, 0x89, 0xec, 0xa3, 0xd7, 0x31, 0xf1, 0xcb, 0x3b,
	0xaf, 0x3b, 0xff, 0xe9, 0xc2, 0xc0, 0x7c, 0x90, 0xf7, 0x99, 0x50, 0x5b, 0xf2, 0x1a, 0xc8, 0x32,
	0x8a, 0x39, 0x4e, 0xcb, 0xdb, 0xad, 0xfd, 0x50, 0x9a, 0x90, 0x72, 0x40, 0xca, 0xd7, 0x36, 0x7e,
	0x50, 0x0d, 0x4d, 0x3e, 0x1d, 0x7e, 0x8b, 0x9c, 0xc3, 0x91, 0x7d, 0x3d, 0x35, 0x01, 0xd3, 0x0f,
	0x4d, 0xc6, 0x65, 0xf9, 0x1f, 0x4f, 0x6c, 0x5c, 0xc9, 0xeb, 0x9a, 0xd6, 0x9b, 0xca, 0x4a, 0x25,
	0x44, 0x1e, 0x36, 0x74, 0xfe, 0x6a, 0x66, 0x01, 0x07, 0xf6, 0x9c, 0xa5, 0x54, 0x28, 0x7e, 0x0f,
	0xb9, 0x69, 0xad, 0x31, 0xf0, 0x7e, 0xeb, 0xb6, 0x87, 0xbf, 0x9c, 0x97, 0xbf, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x91, 0xe6, 0x3e, 0xb2, 0x83, 0x04, 0x00, 0x00,
}
